[package]
name = "csmp-loop-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
csmp-loop-common = { path = "../csmp-loop-common", features = ["user"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

